feeds:
  - https://brandur.org/articles.atom
  - https://brandur.org/fragments.atom
  - https://brandur.org/atoms.atom
  - https://michael-mckenna.com/blog/atom.xml
  - https://waitbutwhy.com/feed
  - https://www.joelonsoftware.com/feed/
  - https://benhoyt.com/writings/rss.xml
  - https://jvns.ca/atom.xml
  - https://feeds.hanselman.com/ScottHanselman
  - https://scott.ee/feed.xml
  - https://blog.bonnieeisenman.com/feed.xml
  - https://schnerring.net/index.xml
  - https://fasterthanli.me/index.xml
  - https://seirdy.one/posts/atom.xml
  - https://muffinman.io/atom.xml
  - https://susam.net/blog/feed.xml
  - https://borretti.me/feed.xml
  - https://devopsjournal.io/blog/atom.xml
  - https://maggieappleton.com/rss.xml
  - https://blog.maartenballiauw.be/feed.xml
  - https://blog.jgc.org/feeds/posts/default
  - https://boffosocko.com/feed/
  - http://feed.looselytyped.net/CJsLooselyTyped
  - https://craftbyzen.com/rss.xml
  - http://feeds.feedburner.com/OdeToCode
  - https://compiledexperience.com/blog/syndicate/rss/
  - https://snarfed.org/feed
  - https://petersmith.org/index.xml
  - https://dri.es/rss.xml
  - https://aegir.org/words/feed
  - https://benthehuman.com/feed
  - https://kevquirk.com/feed
  - https://rachelbythebay.com/w/atom.xml
  - https://blog.jim-nielsen.com/feed.xml
time_zone: Pacific/Auckland
